name: Update README

on:
  push:
    paths:
      - '**.ts' # 監聽 TypeScript 檔案的變更

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Update README
        run: |
          file_list=$(find . -name "*.ts" | sort)        
          readme_content=""

          for file in $file_list; do
            question_number=$(echo "$file" | sed -n 's/.*\([0-9]\{5\}-[^\.]*\.ts\).*/\1/p')
            link="[$question_number](https://github.com/linyawun/type-challenges/blob/main/$file)"
            readme_content="$readme_content- $link\n"
          done

          sed -i '/<!-- GENERATED LIST START -->/,<!-- GENERATED LIST END -->/c\<!-- GENERATED LIST START -->\n'"$readme_content"'<!-- GENERATED LIST END -->' README.md

          git add README.md
          git commit -m "Update README.md"
          git push
